version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      #- "127.0.0.1:4510-4559:4510-4559"  # external services port range -- REMOVED
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=9000
      - TMPDIR=/private$TMPDIR
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=kinesis,lambda,s3,firehose,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./producer-kinesis:/producer-kinesis
      - ./filter-lambda:/filter-lambda
      - ./consumer-lambda:/consumer-lambda
  terraform:
    image: hashicorp/terraform:1.5
    volumes:
      - ./stacks:/stacks
    working_dir: /stacks
volumes:
  localstack-volume:
